# Generated by Django 3.1.4 on 2021-01-28 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_page', '0003_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='settings_profile_json',
            field=models.TextField(default="{\n    profile_photo: 'everyone',\n    profile_bio: 'everyone',\n    posts: 'everyone',\n    last_online: 'nobody',\n}"),
        ),
    ]
