# Generated by Django 3.1.4 on 2021-01-28 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_page', '0004_profile_settings_profile_json'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='settings_profile_json',
            field=models.CharField(default='{"profile_photo": "everyone","profile_bio": "everyone","posts": "everyone","last_online": "nobody"}', max_length=5000),
        ),
    ]
